/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tanhaJava;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import static sun.net.www.http.HttpClient.New;

/**
 *
 * @author Mahdi
 */
public class mainPage extends javax.swing.JFrame {

    public static boolean CircleClick = false;
    public static boolean LineClick = false;
    public static boolean finishClick = false;
    public static boolean head = false;
    public static String selected;
    public static String startFROM;
    public static Node privuse;
    public mainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Finish = new javax.swing.JButton();
        Line = new javax.swing.JButton();
        Circle = new javax.swing.JButton();
        panel1 = new tanhaJava.panel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 150));

        Finish.setBackground(new java.awt.Color(5, 34, 137));
        Finish.setForeground(new java.awt.Color(255, 255, 255));
        Finish.setText("Finish");
        Finish.setBorder(new javax.swing.border.MatteBorder(null));
        Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishActionPerformed(evt);
            }
        });

        Line.setBackground(new java.awt.Color(5, 34, 137));
        Line.setForeground(new java.awt.Color(255, 255, 255));
        Line.setText("Line");
        Line.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        Line.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineActionPerformed(evt);
            }
        });

        Circle.setBackground(new java.awt.Color(5, 34, 137));
        Circle.setForeground(new java.awt.Color(255, 255, 255));
        Circle.setText("Circle");
        Circle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        Circle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CircleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Line, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(Finish, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(Circle, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Line, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Finish, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Circle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineActionPerformed

Color myBlue=new Color(5,34,137);

        this.LineClick = !this.LineClick;
        this.CircleClick = false;
        Circle.setBackground(myBlue);
        Finish.setBackground(myBlue);
        if(this.LineClick){
        Line.setBackground(Color.red);
        }
        else {
        Line.setBackground(myBlue);
        
        }
    }//GEN-LAST:event_LineActionPerformed

    private void FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishActionPerformed
        // TODO add your handling code here:
    
Color myBlue=new Color(5,34,137);

        this.LineClick=false;
        this.CircleClick=false;
        Circle.setBackground(myBlue);
        Line.setBackground(myBlue);
        Finish.setBackground(Color.red);
        ArrayList <Integer> data;
        String[] list = {"BFS", "DFS" };
        if(panel.haveNodes){
           if(panel.haveConnection){
               mainPage.selected = (String) JOptionPane.showInputDialog( this, 
               "Graph transveling ", "Graph transveling :",
               JOptionPane.INFORMATION_MESSAGE, null,
               list, list[0]);
               if(mainPage.selected.length()!=0){
                   Integer[] series = {};
                     for(Node circle : panel.circleList){ 
                          series = addElement(series, circle.Name);
                     }
                   if(mainPage.selected.equals("BFS")){
                       
                       mainPage.finishClick = true;
             int startFrom = (Integer) JOptionPane.showInputDialog( this, 
               "select node ", "start from :",
               JOptionPane.INFORMATION_MESSAGE, null,series,series[0]);
              
                       data = BFS.handleBfs(startFrom);
                       
                       System.out.println(data);
                       Thread thread;
                       thread = new Thread(){
                           
                           public void run(){
                               for (Integer data1 : data) {
                                   panel.data = data1;
                                   repaint();
                                   System.out.println("Thread Running");
                                    try {
                                          Thread.sleep(2000);
                                        } 
                                    catch (InterruptedException ex) {
                                    }
                               }
                               
                               
                                SwingUtilities.invokeLater(new Runnable() {
                                        @Override
                                        public void run() {
                                                mainPage.finishClick = false;
                                                repaint();
                                                JOptionPane.showMessageDialog(null, "finish");
                                        }
                                });
                               
                           }
                           
                       };
                       thread.start();         
                   }
                   
                   else if(mainPage.selected.equals("DFS"))
                   {
                       mainPage.finishClick = true;
          
                       DFS f = new DFS();
                       data = f.DFSFunction();
                       Thread thread;
                       thread = new Thread(){
                           
                           public void run(){
                               for (Integer data1 : data) {
                                   panel.data = data1;
                                   repaint();
                                   System.out.println("Thread Running");
                                    try {
                                          Thread.sleep(2000);
                                        } 
                                    catch (InterruptedException ex) {
                                    }
                               }
                               
                               
                                SwingUtilities.invokeLater(new Runnable() {
                                        @Override
                                        public void run() {
                                                mainPage.finishClick = false;
                                                repaint();
                                                JOptionPane.showMessageDialog(null, "finish");
                                        }
                                });
                               
                           }
                           
                       };
                       thread.start();
                       
                   } 
               }
           }
           else{
               JOptionPane.showMessageDialog(null, "not have any connection", "Dialog",
        JOptionPane.ERROR_MESSAGE);
           }
       }
       else{
             JOptionPane.showMessageDialog(null, "not have any nodes", "Dialog",
        JOptionPane.ERROR_MESSAGE);
       }
   
    }//GEN-LAST:event_FinishActionPerformed

    private void CircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CircleActionPerformed

Color myBlue=new Color(5,34,137);

        Line.setBackground(myBlue);
        Finish.setBackground(myBlue);
        this.CircleClick = !this.CircleClick;
        this.LineClick = false;
        if(this.CircleClick){
          Circle.setBackground(Color.red);
        }
        else{            
          Circle.setBackground(myBlue);
        }
    }//GEN-LAST:event_CircleActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPage().setVisible(true);
            }
        });
    }
    @Override
    public void paintComponents(Graphics g){
  
        
    }
    static Integer[] addElement(Integer[] a, int e) {
    a  = Arrays.copyOf(a, a.length + 1);
    a[a.length - 1] = e;
    return a;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Circle;
    private javax.swing.JButton Finish;
    private javax.swing.JButton Line;
    private javax.swing.JPanel jPanel1;
    public static tanhaJava.panel panel1;
    // End of variables declaration//GEN-END:variables
}
